/** Shared colours for the 3D stand-ins.
 * Region palettes are the exact hex values the 2D game uses in levels.ts, so a
 * stand-in diorama reads as the same place as the painted 2D background.
 */
export const REGIONS = [
  {
    id: 'fields',
    name: 'Sunseed Fields',
    mission: 0,
    gravity: 1,
    sky: '#739cae',
    haze: '#f8c479',
    accent: '#ffdf7a',
    ground: '#456747',
    sun: '#fff1c2',
    enemies: ['shadeHound', 'seedSpitter'],
    landmark: 'crownlineSkyline',
  },
  {
    id: 'city',
    name: 'Crownline City',
    mission: 0,
    gravity: 1,
    sky: '#b98687',
    haze: '#f6bd86',
    accent: '#a1efe3',
    ground: '#465663',
    sun: '#ffd9a0',
    enemies: ['windowRay', 'spireLeech'],
    landmark: 'thunderheadSummit',
  },
  {
    id: 'mountains',
    name: 'Thunderhead Range',
    mission: 0,
    gravity: 1,
    sky: '#7c8d9c',
    haze: '#d5ad8d',
    accent: '#e9d09b',
    ground: '#535963',
    sun: '#f4e2c4',
    enemies: ['cragTortoise', 'riftCondor'],
    landmark: 'transmitterMast',
  },
  {
    id: 'foundry',
    name: 'Cinder Foundries',
    mission: 1,
    gravity: 1,
    sky: '#644d45',
    haze: '#c28754',
    accent: '#ffb454',
    ground: '#4d4345',
    sun: '#ffb070',
    enemies: ['furnaceHound', 'slagCaster'],
    landmark: 'craneForest',
  },
  {
    id: 'harbor',
    name: 'Tempest Docks',
    mission: 1,
    gravity: 1,
    sky: '#667d84',
    haze: '#b1c0b5',
    accent: '#b4f2df',
    ground: '#3e5d61',
    sun: '#d9e6dc',
    enemies: ['chainManta', 'ballastCrab'],
    landmark: 'launchSpine',
  },
  {
    id: 'launchworks',
    name: 'Skyhook Works',
    mission: 1,
    gravity: 1,
    sky: '#a5a9a5',
    haze: '#efe0bd',
    accent: '#ffd38c',
    ground: '#716566',
    sun: '#fff3d2',
    enemies: ['coilWraith', 'turbineWasp'],
    landmark: 'starGate',
  },
  {
    id: 'red',
    name: 'Vermilion Basin',
    mission: 2,
    gravity: 1.35,
    sky: '#6c2533',
    haze: '#de765d',
    accent: '#fff0bc',
    ground: '#9a4348',
    sun: '#1a0a10',
    enemies: ['basaltBurrower', 'thornChoir'],
    landmark: 'blackSun',
  },
  {
    id: 'blue',
    name: 'Cobalt Drift',
    mission: 2,
    gravity: 0.55,
    sky: '#193d77',
    haze: '#478bab',
    accent: '#b9fff1',
    ground: '#355d91',
    sun: '#cfe9ff',
    enemies: ['veilMedusa', 'phaseSkate'],
    landmark: 'driftMoon',
  },
  {
    id: 'violet',
    name: 'Violet Inversion',
    mission: 2,
    gravity: 0.85,
    sky: '#251633',
    haze: '#60436c',
    accent: '#e5b8ff',
    ground: '#503653',
    sun: '#100616',
    enemies: ['mirrorStalker', 'gravityCantor'],
    landmark: 'eclipseCathedral',
  },
];

export const regionById = (id) => REGIONS.find((r) => r.id === id);

/** Hopper's own colours from the canonical sheet. */
export const HOPPER = {
  green: '#3f8a3c',
  greenDark: '#2b5f2c',
  cream: '#efe3c4',
  red: '#c8352b',
  blue: '#2f5f9a',
  gold: '#c99a3c',
  eye: '#d9271f',
  joint: '#3a3838',
  riderShirt: '#f1e8d2',
  riderShorts: '#2d4c7c',
  riderScarf: '#d13a2c',
  riderHair: '#1e1a1a',
  riderSkin: '#f0c9a4',
};

/** Shadow creature language: charcoal interiors, violet contours, pale cores. */
export const SHADOW = {
  body: '#1a1520',
  bodyDeep: '#0e0b12',
  edge: '#8a4bd8',
  core: '#f3e7c8',
  coreHot: '#ff8a2a',
  furnace: '#ff6a1f',
  eye: '#f8f1d8',
  mask: '#e9dfc5',
  chain: '#4a4048',
  glow: '#c9ffe5',
};

/** Material palette shared by the structure kits. */
export const SURFACE = {
  ivory: '#e8e0c8',
  ivoryShade: '#c9bfa3',
  tealGlass: '#5fb7a6',
  slate: '#5c626d',
  basalt: '#3d3b44',
  iron: '#3c3b3f',
  ironWarm: '#5a4d47',
  rust: '#9a5a33',
  wetSteel: '#4f6b6c',
  concrete: '#b8b3a4',
  soil: '#7a5a3c',
  grass: '#5f8f3f',
  grassDeep: '#3f6b33',
  wood: '#8c6a3f',
  coral: '#b7322c',
  bone: '#efe5cf',
  reef: '#3f7fb5',
  reefGlow: '#8fe8ff',
  obsidian: '#2a1e34',
  obsidianEdge: '#a56cff',
  water: '#2f5f7a',
  lava: '#ff7a22',
};
